Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-10, with the labels that each got.

#585 Revert "Remove unnecessary keystoneauth patch (#580)"
  terraform/files/bin/prepare_openstack.sh
  terraform/files/fix-keystoneauth-plugins-unversioned.diff
  terraform/mgmtcluster.tf
Labels: bug, Container

#581 Add e2e conformance test for R5 and for the latest version of the code
  .zuul.yaml
  README.md
  doc/continuous-integration.md
Labels: Container

#590 Backport sprint Hobart to `maintained/v5.0.x` #530
  terraform/files/bin/clusterctl_template.sh
Labels: Container, Sprint Hobart

#604 Fix daily pipeline
  .zuul.yaml
Labels: Container

#614 Add an Ansible lint GitHub action and supply the required code modifications
  .ansible-lint
  .github/workflows/ansible-lint.yml
  playbooks/cleanup.yaml
  playbooks/dependencies.yaml
  playbooks/e2e.yaml
Labels: Container, successful-e2e-quick-test

#616 Add "stale" GitHub Action
  .github/workflows/stale.yml
Labels: Container

#624 Preserves (possible) additional docker-daemon settings
  terraform/files/bin/get_mtu.sh
Labels: successful-e2e-quick-test

#627 Fix Calico/Cilium typo in R5 Upgrade Guide
  doc/Upgrade-Guide.md
Labels: Container

#608 Update terraform cache directory for providers
  terraform/Makefile
Labels: bug, Container

#621 Add checkout to PR banch into e2e tests
  playbooks/e2e.yaml
Labels: Container

#610 Support custom zuul configs #433
  doc/continuous-integration.md
  playbooks/cleanup.yaml
  playbooks/e2e.yaml
  playbooks/templates/environment.tfvars.j2
Labels: Container, Sprint Nantes

#617 Install kubectx on management node #457
  Release-Notes-R6.md
  terraform/files/bin/bootstrap.sh
  terraform/files/bin/install_kubectx.sh
Labels: enhancement, Container, Sprint Nantes

#618 Install kube_ps1 on management node #458
  Release-Notes-R6.md
  terraform/files/bin/bootstrap.sh
  terraform/files/bin/install_kube_ps1.sh
Labels: enhancement, Container, Sprint Nantes
