Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-11, with the labels that each got.

#639 Delete "*sets" before k8s pods to ensure we enumerate all of them.
  terraform/files/bin/delete_cluster.sh
Labels: e2e-quick-test

#638 Backport sprint Izmir to maintained/v5.x #531
  Release-Notes-R5.md
  doc/configuration.md
  doc/usage/containter-registry-configuration.md
  doc/usage/harbor.md
  terraform/environments/environment-default.tfvars
  terraform/files/bin/apply_cert_manager.sh
  terraform/files/bin/apply_cindercsi.sh
  terraform/files/bin/apply_nginx_ingress.sh
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/deploy_harbor.sh
  terraform/files/kubernetes-manifests.d/harbor/base/kustomization.yaml
  terraform/files/kubernetes-manifests.d/harbor/envs/clusterIP/harbor-config.yaml
  terraform/files/kubernetes-manifests.d/harbor/envs/clusterIP/kustomization.yaml
  terraform/files/kubernetes-manifests.d/harbor/envs/ingress/harbor-config.yaml
  terraform/files/kubernetes-manifests.d/harbor/envs/ingress/issuer.yaml
  terraform/files/kubernetes-manifests.d/harbor/envs/ingress/kustomization.yaml
  terraform/files/template/harbor-settings.tmpl
  terraform/mgmtcluster.tf
  terraform/variables.tf
Labels: Sprint Izmir

#583 Fix logic for non-influencing execution of scripts
  terraform/files/bin/add_cluster-network.sh
  terraform/files/bin/apply_cert_manager.sh
  terraform/files/bin/apply_cindercsi.sh
  terraform/files/bin/apply_metrics.sh
  terraform/files/bin/apply_nginx_ingress.sh
  terraform/files/bin/apply_openstack_integration.sh
  terraform/files/bin/cccfg.inc
  terraform/files/bin/configure_containerd.sh
  terraform/files/bin/create_appcred.sh
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/delete_cluster.sh
  terraform/files/bin/handle_ovn_lb.sh
  terraform/files/bin/mng_cluster_ns.inc
  terraform/files/bin/remove_cluster-network.sh
  terraform/files/bin/utils.inc
  terraform/files/bin/wait_capi_image.sh
Labels: Container

#625 Fix kubeapi cidr restrictions
  terraform/files/bin/apply_kubeapi_cidrs.sh
Labels: bug, Container

#600 Add ClusterClass
  doc/usage/migrate-to-cluster-class.md
  terraform/cleanup/cleanup.sh
  terraform/files/bin/apply_kubeapi_cidrs.sh
  terraform/files/bin/configure_containerd.sh
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/deploy_cluster_api.sh
  terraform/files/bin/inject_custom_ca.sh
  terraform/files/bin/migrate-to-cluster-class.sh
  terraform/files/kubernetes-manifests.d/rmv-vol-from-ctrl.yaml
  terraform/files/kubernetes-manifests.d/rmv-vol-from-worker.yaml
  terraform/files/template/cluster-template.yaml
  terraform/files/template/clusterctl.yaml.tmpl
Labels: enhancement, Container

#645 Proxy settings for controlplane and worker nodes
  terraform/files/bin/configure_containerd_proxy.sh
  terraform/files/bin/configure_proxy.sh
  terraform/files/bin/create_cluster.sh
  terraform/files/template/cluster-template.yaml
Labels: successful-e2e-quick-test

#651 New config-setting no_proxy
  doc/configuration.md
  terraform/files/bin/configure_containerd_proxy.sh
  terraform/mgmtcluster.tf
  terraform/variables.tf
Labels: successful-e2e-quick-test
