Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-09, with the labels that each got.

#544 Update default calico to 3.26.1
  Release-Notes-R5.md
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/files/kubernetes-manifests.d/calico.yaml
  terraform/variables.tf
Labels: enhancement, Container

#542 Update default ingress-nginx to 1.8.1
  Release-Notes-R5.md
  doc/configuration.md
  doc/usage/containter-registry-configuration.md
  terraform/files/bin/apply_nginx_ingress.sh
  terraform/files/bin/update-R4-to-R5.sh
  terraform/files/kubernetes-manifests.d/nginx-ingress/base/nginx-ingress-controller-v1.8.1.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-monitor/nginx-monitor.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-nomonitor/nginx-nomonitor.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-proxy/nginx-monitor.yaml
Labels: enhancement, Container

#539 Update helm to 3.12.3
  terraform/files/bin/install_helm.sh
Labels: enhancement, Container

#540 Update default cert-manager to 1.12.4
  doc/configuration.md
  terraform/files/bin/apply_cert_manager.sh
Labels: enhancement, Container

#546 Update default cilium to 1.14.1
  Release-Notes-R5.md
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/files/bin/create_cluster.sh
  terraform/variables.tf
Labels: enhancement, Container

#547 Update flux release notes
  Release-Notes-R5.md
  doc/configuration.md
Labels: enhancement, Container

#549 Update default k8s to 1.27
  Release-Notes-R5.md
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/deploy_cluster_api.sh
  terraform/files/bin/install_kind.sh
  terraform/files/bin/openstack-kube-versions.inc
  terraform/variables.tf
Labels: enhancement, Container

#545 Update release notes R5
  Release-Notes-R5.md
Labels: documentation, Container

#552 Feat/limit kube apiserv mem
  Release-Notes-R5.md
  terraform/files/template/cluster-template.yaml
Labels: enhancement, Container, Sprint Jena

#551 Update delete_cluster.sh to more thoroughly delete all k8s resources
  terraform/Makefile
  terraform/cleanup/cleanup.sh
  terraform/files/bin/delete_cluster.sh
Labels: enhancement, Container, Sprint Jena

#548 Update R4-to-R5 update script and related upgrade guide doc
  doc/Upgrade-Guide.md
  terraform/files/bin/update-R4-to-R5.sh
  terraform/files/update/R4_to_R5/update-cluster-template.diff
Labels: Container

#559 Fix grepping of PREFIX in Makefile
  terraform/Makefile
Labels: bug, Container

#556 Small typo fixes
  doc/quickstart.md
  doc/requirements.md
  doc/usage/usage.md
Labels: documentation, Container

#557 Node images was moved to REGIO.cloud
  doc/usage/cluster-mgmt-capi-mgmt-node.md
  terraform/files/bin/openstack-kube-versions.inc
  terraform/files/bin/upload_capi_image.sh
Labels: on hold, Container

#555 Add external network autodetection to R5 notes
  Release-Notes-R5.md
Labels: documentation, Container

#534 Add CI E2E testing for k8s-cluster-api-provider project
  .zuul.yaml
  doc/continuous-integration.md
  playbooks/cleanup.yaml
  playbooks/dependencies.yaml
  playbooks/e2e.yaml
  playbooks/templates/environment.tfvars.j2
Labels: enhancement, Container, successful-e2e-test, successful-e2e-quick-test

#560 Improve make purge
  terraform/Makefile
Labels: enhancement, Container

#566 Remove hardcoded ubuntu home folder
  doc/LoadBalancer-ExtTrafficLocal.md
  doc/configuration.md
  doc/overview.md
  doc/usage/containter-registry-configuration.md
  terraform/files/bin/get_mtu.sh
  terraform/mgmtcluster.tf
Labels: enhancement, Container

#575 Update default flux2 to 2.1.0
  Release-Notes-R5.md
  doc/Upgrade-Guide.md
  terraform/files/bin/bootstrap.sh
Labels: successful-e2e-quick-test

#576 Fix warning `grep: warning: stray \ before -` in `cleanup/cleanup.sh`
  terraform/cleanup/cleanup.sh
Labels: bug, Container

#580 Remove unnecessary keystoneauth patch
  terraform/files/bin/prepare_openstack.sh
  terraform/files/fix-keystoneauth-plugins-unversioned.diff
  terraform/mgmtcluster.tf
Labels: housekeeping, Container

#579 Fix curl warning
  terraform/files/bin/deploy_cluster_api.sh
Labels: housekeeping, Container

#587 Update default CAPO to 0.8.0
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/files/bin/apply_kubeapi_cidrs.sh
  terraform/files/kubernetes-manifests.d/add-vol-to-ctrl.yaml
  terraform/files/kubernetes-manifests.d/add-vol-to-worker.yaml
  terraform/files/kubernetes-manifests.d/rmv-vol-from-ctrl.yaml
  terraform/files/kubernetes-manifests.d/rmv-vol-from-worker.yaml
  terraform/files/template/cluster-template.yaml
  terraform/variables.tf
Labels: successful-e2e-quick-test

#597 Update dependency kubernetes-sigs/cluster-api to v1.5.2
  doc/configuration.md
  terraform/variables.tf
Labels: successful-e2e-quick-test
