Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-08, with the labels that each got.

#485 Update github actions
  .github/workflows/check-terraform-syntax.yml
  .github/workflows/check-yaml-syntax.yml
Labels: enhancement, Container

#489 Pass conformance tests with cilium
  terraform/files/bin/create_cluster.sh
Labels: Container

#431 Make cilium the default CNI.
  Release-Notes-R5.md
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/variables.tf
Labels: enhancement, work in progress, Container, SCS-VP06a, SCS is opinionated, Sprint Edmonton

#493 Ensure kubeconfig for cluster namespaces
  terraform/files/bin/delete_cluster.sh
  terraform/files/bin/mng_cluster_ns.inc
Labels: Container

#494 Fix delete_cluster.sh and others to handle per cluster ns on os #492
  terraform/files/bin/add_cluster-network.sh
  terraform/files/bin/delete_cluster.sh
  terraform/files/bin/enable-cilium-sg-kube.sh
  terraform/files/bin/mng_cluster_ns.inc
  terraform/files/bin/remove_cluster-network.sh
Labels: bug, Container

#498 Fix/fullclean namespace
  terraform/Makefile
  terraform/cleanup/cleanup.sh
Labels: bug, Container

#497 Improve mng_cluster_ns.inc messaging #496
  terraform/files/bin/create_appcred.sh
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/mng_cluster_ns.inc
Labels: bug, Container

#503 Enables ciliums implementation of Gateway API
  Release-Notes-R5.md
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/files/bin/create_cluster.sh
  terraform/files/template/clusterctl.yaml.tmpl
  terraform/mgmtcluster.tf
  terraform/variables.tf
Labels: enhancement, Container

#509 Feat/support debian12
  doc/configuration.md
  terraform/Makefile
  terraform/files/bin/bootstrap.sh
  terraform/files/bin/prepare_openstack.sh
  terraform/mgmtcluster.tf
Labels: enhancement, Container

#508 Detect yq being wrapper around jq and handle.
  terraform/Makefile
Labels: bug, Container

#527 Fix harbor-settings no such file
  terraform/files/bin/create_cluster.sh
Labels: bug, Container

#518 Add installation of jq into the `update-R4-to-R5.sh` and release notes
  Release-Notes-R5.md
  terraform/files/bin/update-R4-to-R5.sh
Labels: bug, Container

#526 Feat/remove att volumes
  doc/make-reference.md
  terraform/Makefile
  terraform/cleanup/cleanup.sh
Labels: enhancement, Container, Sprint Jena

#524 flavor_disk.sh Installs jq when it is missing #500
  terraform/files/bin/flavor_disk.sh
Labels: bug, Container
