Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-12, with the labels that each got.

#656 Fix metrics server upgrade
  terraform/files/bin/apply_metrics.sh
Labels: bug, Container

#660 Backport sprint Jena to `maintained/v5.x` #532
  Release-Notes-R5.md
  doc/configuration.md
  doc/usage/containter-registry-configuration.md
  doc/usage/harbor.md
  terraform/Makefile
  terraform/environments/environment-default.tfvars
  terraform/files/bin/apply_cert_manager.sh
  terraform/files/bin/apply_metrics.sh
  terraform/files/bin/apply_nginx_ingress.sh
  terraform/files/bin/bootstrap.sh
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/deploy_cluster_api.sh
  terraform/files/bin/deploy_harbor.sh
  terraform/files/bin/flavor_disk.sh
  terraform/files/bin/install_helm.sh
  terraform/files/bin/install_kind.sh
  terraform/files/bin/openstack-kube-versions.inc
  terraform/files/bin/prepare_openstack.sh
  terraform/files/kubernetes-manifests.d/calico.yaml
  terraform/files/kubernetes-manifests.d/harbor/base/kustomization.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/base/nginx-ingress-controller-v1.8.1.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-monitor/nginx-monitor.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-nomonitor/nginx-nomonitor.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-proxy/nginx-monitor.yaml
  terraform/main.tf
  terraform/mgmtcluster.tf
  terraform/variables.tf
Labels: Container, Sprint Jena

#665 Adds make-target do deploy cluster-stack-operator
  doc/make-reference.md
  terraform/Makefile
  terraform/files/kubernetes-manifests.d/cso.yaml
Labels: successful-e2e-quick-test

#664 Bump latest versions of k8s and occm:
  terraform/files/bin/openstack-kube-versions.inc
Labels: Container
