Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-02, with the labels that each got.

#315 Feat/latest k8s 202301
  terraform/files/bin/cccfg.inc
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/fixup_k8s_version.sh
  terraform/files/bin/openstack-kube-versions.inc
Labels: enhancement, Container

#319 Move to kind-0.17.0 (k8s v1.25.3).
  terraform/files/bin/install_kind.sh
Labels: enhancement, Container

#323 Modify LB IP with dns suffix when the proxy protocol is used
  terraform/files/template/cloud.conf.tmpl
Labels: bug, Container

#324 Address #321: Finegrained repo location patching.
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/fixup_k8sregistry.sh
Labels: bug, Container

#322 Correct occm and ccsi image versions
  terraform/files/bin/apply_cindercsi.sh
  terraform/files/bin/apply_openstack_integration.sh
Labels: Container

#327 Update to latest k8s and occm patch
  terraform/files/bin/openstack-kube-versions.inc
Labels: enhancement, Container
