Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-06, with the labels that each got.

#427 Update CAPI to v1.3.8 and CAPO to 0.7.3.
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/variables.tf
Labels: enhancement, Container, Sprint Edmonton

#429 Feat/calico 3.25.1
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/variables.tf
Labels: enhancement, Container

#428 Update to latest k8s and latest occm versions.
  terraform/files/bin/openstack-kube-versions.inc
Labels: enhancement, Container, Sprint Edmonton

#422 Replace k8s registry locations (#412)
  terraform/files/bin/create_cluster.sh
  terraform/files/bin/fixup_k8sregistry.sh
  terraform/files/kubernetes-manifests.d/nginx-ingress/base/nginx-ingress-controller-v1.1.2.yaml
  terraform/files/template/cluster-template.yaml
Labels: housekeeping, Container

#430 Feat/cilium 1.13.3
  doc/configuration.md
  terraform/environments/environment-default.tfvars
  terraform/files/bin/create_cluster.sh
  terraform/variables.tf
Labels: enhancement, Container

#439 Update helm to 3.12.1
  Release-Notes-R5.md
  terraform/files/bin/install_helm.sh
Labels: enhancement, Container

#438 Update kind to 0.18.0
  Release-Notes-R5.md
  terraform/files/bin/install_kind.sh
Labels: enhancement, Container

#437 Update default cert-manager to 1.12.2
  Release-Notes-R5.md
  doc/configuration.md
  terraform/files/bin/apply_cert_manager.sh
Labels: enhancement, Container

#436 Update sonobuoy to 0.56.17
  Release-Notes-R5.md
  terraform/files/bin/sonobuoy.sh
Labels: enhancement, Container

#435 Update default flux2 to 0.41.2
  Release-Notes-R5.md
  terraform/files/bin/bootstrap.sh
Labels: enhancement, Container

#426 Use tf-1.3.6 for github workflow.
  .github/workflows/check-terraform-syntax.yml
  Release-Notes-R5.md
  terraform/main.tf
Labels: bug, Container, Sprint Edmonton

#441 Bump cilium version in configuration doc
  doc/configuration.md
Labels: enhancement, Container

#442 Update metrics-server to 0.6.3
  Release-Notes-R5.md
  terraform/files/bin/apply_metrics.sh
Labels: enhancement, Container

#444 Feat/k9s pin
  Release-Notes-R5.md
  terraform/Makefile
  terraform/files/bin/install_k9s.sh
Labels: enhancement, Container

#440 Update default ingress-nginx to 1.8.0
  Release-Notes-R5.md
  doc/configuration.md
  terraform/files/bin/apply_nginx_ingress.sh
Labels: enhancement, Container
