Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2023-03, with the labels that each got.

#326 Fix needrestart configuration
  terraform/files/bin/prepare_openstack.sh
  terraform/mgmtcluster.tf
Labels: Container

#350 Format tables in README.md
  README.md
Labels: documentation, Container

#354 Add prefix to security groups allow-ssh and allow-icmp
  terraform/cleanup/cleanup.sh
  terraform/files/template/cluster-template.yaml
  terraform/neutron.tf
Labels: Container

#349 Fix cluster API load balancer lookup in the cleanup script
  terraform/cleanup/cleanup.sh
Labels: Container

#353 Upgrade CAPI to v1.3.5 and CAPO to v0.7.1
  README.md
  Release-Notes-R4-draft.md
  terraform/environments/environment-default.tfvars
  terraform/files/bin/openstack-kube-versions.inc
  terraform/files/template/cluster-template.yaml
  terraform/variables.tf
Labels: Container

#348 Adjust to new kustomize syntax.
  terraform/files/bin/kustpatch.sh
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-monitor/kustomization.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-nomonitor/kustomization.yaml
  terraform/files/kubernetes-manifests.d/nginx-ingress/nginx-proxy/kustomization.yaml
Labels: bug, Container

#345 Some small improvements to the main doc.
  README.md
Labels: documentation, Container

#363 Remove deprecated ETCD_PRIO_BOOST.
  README.md
  terraform/environments/environment-default.tfvars
  terraform/files/template/clusterctl.yaml.tmpl
  terraform/mgmtcluster.tf
  terraform/variables.tf
Labels: enhancement, Container

#358 Update sonobuoy to 0.56.16.
  Release-Notes-R4-draft.md
  terraform/files/bin/sonobuoy.sh
Labels: enhancement, Container

#356 Change default k8s version to v1.25.x (x=latest).
  README.md
  terraform/environments/environment-default.tfvars
  terraform/variables.tf
Labels: enhancement, Container

#355 Feat/protect etcd backup
  terraform/files/template/cluster-template.yaml
Labels: bug, Container

#371 Add --grouping=false to clusterctl describe cluster.
  terraform/files/bin/create_cluster.sh
Labels: enhancement, Container

#362 Use new v2 flavor names.
  README.md
  terraform/environments/environment-default.tfvars
  terraform/variables.tf
Labels: enhancement, Container

#387 Quickfix for #384: Don't defrag etcd on leader.
  terraform/files/template/cluster-template.yaml
Labels: bug, Container

#396 Fix/use cilium readme 2
  doc/configuration.md
Labels: documentation, Container

#388 Update Upgrade-Guide with respect to R4
  doc/Upgrade-Guide.md
Labels: documentation, Container

#393 Text for the most important topics filled.
  Release-Notes-R4.md
Labels: documentation, Container

#397 Move README to OLD_README with the intention to remove it.
  OLD_README.md
  README.md
Labels: documentation, Container

#402 Release date of R4 is Mar 2023, not 2024 of course.
  Release-Notes-R4.md
Labels: documentation, Container

#405 Feat/final rn4 touches
  README.md
  Release-Notes-R4.md
Labels: documentation, Container

#401 Update etcd defrag and backup
  doc/Maintenance_and_Troubleshooting.md
  terraform/files/template/cluster-template.yaml
Labels: Container
