Repository SovereignCloudStack/k8s-cluster-api-provider, pull requests merged in 2024-03, with the labels that each got.

#711 Upgrade R5 to R6
  doc/Upgrade-Guide.md
  terraform/files/bin/migrate-to-cluster-class.sh
  terraform/files/bin/update-R5-to-R6.sh
Labels: documentation, enhancement, Container, Sprint Wellington, kaas-hackathon

#713 Add Release notes for R6
  Release-Notes-R6.md
  doc/configuration.md
Labels: documentation, Container

#716 Deploy latest cso and cspo
  doc/make-reference.md
  terraform/Makefile
  terraform/files/kubernetes-manifests.d/cso.yaml
  terraform/files/kubernetes-manifests.d/cspo.yaml
Labels: Container

#718 Add generation counter for the OpenStackClusterTemplate and fix externalNetworkId
  doc/Upgrade-Guide.md
  doc/configuration.md
  doc/usage/migrate-to-cluster-class.md
  terraform/files/bin/apply_kubeapi_cidrs.sh
  terraform/files/bin/migrate-to-cluster-class.sh
  terraform/files/bin/update-R5-to-R6.sh
  terraform/files/template/cluster-template.yaml
  terraform/files/template/clusterctl.yaml.tmpl
Labels: Container, successful-e2e-quick-test

#714 Add scs-0210-v2 and scs-0214-v1 zuul checks
  .zuul.yaml
  playbooks/e2e.yaml
  playbooks/tasks/label_nodes.yaml
  playbooks/tasks/scs_compliance.yaml
  playbooks/tasks/sonobouy.yaml
  playbooks/templates/environment.tfvars.j2
Labels: successful-e2e-quick-test, failed-e2e-test
